# .github/workflows/ci.yml
name: Build Skillify (JAR)

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build fat jar without tests
        working-directory: java
        run: mvn clean package -DskipTests

      - name: Upload fat JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: skillify
          path: java/target/skillify.jar
